#ifndef __DEFINES_H_INCLUDED__
#define __DEFINES_H_INCLUDED__

#include "deque.h"

#define CLIENT_GONE 0x2
#define CLIENT_CREATED 0x1
#define CLIENT_ASSIGNED 0xA
#define CLIENT_ENDED_COURSE 0x3

#define BIKE_CREATED 0x5
#define BIKE_ASSIGNED 0xC

#define WAIT_UNTIL_SCHEDULE 10

#endif // __DEFINES_H_INCLUDED__